### ISSUE TITLE
aeGis does not respond to text message if location cannot be obtained

### ISSUE THREAD

**Issue by c00ller** [Decad3nce/Aegis#72]
I tested aeGis in my room, where I am unable to obtain a GPS lock. I'm looking at GPS Monitor app, which says only 2 satellites in view, 1 locked. The result is aeGis isn't sending any text message responses. aeGis should at least respond with a confirmation alerting the user that location is being attempted, but could not due to poor reception.

In my room, aeGis locator works fine if WiFi is connected.

The current "do nothing" situation makes the user wonder if the phone even received the text message, and if it did, if aeGis is malfunctioning.

**Comment by Decad3nce** [comment]
The first reply should always be from the network. Subsequent attempts try to get a "better" location that that. 

So I don't know how to change that, since that's what is intended.

**Comment by c00ller** [comment]
To clarify, in my case aeGis never sent a first reply at all. What exactly do you mean by the first reply should always be from the network while subsequent attempts try to get a "better" location"?

**Comment by Decad3nce** [comment]
If it never sent a first reply, that means a lock was never done at all. 

The first track as mFirstTrack within PhoneTrackerActivity tells the device to do very inaccurate tracking to give the user a response.

What you're requesting is that an SMS is to be sent to the originating address that states that aeGis is actively tracking.(which I might have removed, because I could swear it used to)

**Comment by Decad3nce** [comment]
This is fixed
